/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminRoomsRouteImport } from './routes/_admin.rooms'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin.users.index'
import { Route as AdminSubjectsIndexRouteImport } from './routes/_admin.subjects.index'
import { Route as AdminHistoryIndexRouteImport } from './routes/_admin.history.index'
import { Route as AdminArtistsIndexRouteImport } from './routes/_admin.artists.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/_admin.users.$userId'
import { Route as AdminSubjectsSubjectIdRouteImport } from './routes/_admin.subjects.$subjectId'
import { Route as AdminHistoryHistoryIdRouteImport } from './routes/_admin.history.$historyId'
import { Route as AdminArtistsArtistIdRouteImport } from './routes/_admin.artists.$artistId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsIndexRoute = AdminSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoryIndexRoute = AdminHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistsIndexRoute = AdminArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsSubjectIdRoute = AdminSubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoryHistoryIdRoute = AdminHistoryHistoryIdRouteImport.update({
  id: '/history/$historyId',
  path: '/history/$historyId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistsArtistIdRoute = AdminArtistsArtistIdRouteImport.update({
  id: '/artists/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/rooms': typeof AdminRoomsRoute
  '/artists/$artistId': typeof AdminArtistsArtistIdRoute
  '/history/$historyId': typeof AdminHistoryHistoryIdRoute
  '/subjects/$subjectId': typeof AdminSubjectsSubjectIdRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/artists/': typeof AdminArtistsIndexRoute
  '/history/': typeof AdminHistoryIndexRoute
  '/subjects/': typeof AdminSubjectsIndexRoute
  '/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/rooms': typeof AdminRoomsRoute
  '/': typeof AdminIndexRoute
  '/artists/$artistId': typeof AdminArtistsArtistIdRoute
  '/history/$historyId': typeof AdminHistoryHistoryIdRoute
  '/subjects/$subjectId': typeof AdminSubjectsSubjectIdRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/artists': typeof AdminArtistsIndexRoute
  '/history': typeof AdminHistoryIndexRoute
  '/subjects': typeof AdminSubjectsIndexRoute
  '/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/_admin/rooms': typeof AdminRoomsRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/artists/$artistId': typeof AdminArtistsArtistIdRoute
  '/_admin/history/$historyId': typeof AdminHistoryHistoryIdRoute
  '/_admin/subjects/$subjectId': typeof AdminSubjectsSubjectIdRoute
  '/_admin/users/$userId': typeof AdminUsersUserIdRoute
  '/_admin/artists/': typeof AdminArtistsIndexRoute
  '/_admin/history/': typeof AdminHistoryIndexRoute
  '/_admin/subjects/': typeof AdminSubjectsIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/rooms'
    | '/artists/$artistId'
    | '/history/$historyId'
    | '/subjects/$subjectId'
    | '/users/$userId'
    | '/artists/'
    | '/history/'
    | '/subjects/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/rooms'
    | '/'
    | '/artists/$artistId'
    | '/history/$historyId'
    | '/subjects/$subjectId'
    | '/users/$userId'
    | '/artists'
    | '/history'
    | '/subjects'
    | '/users'
  id:
    | '__root__'
    | '/_admin'
    | '/forbidden'
    | '/login'
    | '/_admin/rooms'
    | '/_admin/'
    | '/_admin/artists/$artistId'
    | '/_admin/history/$historyId'
    | '/_admin/subjects/$subjectId'
    | '/_admin/users/$userId'
    | '/_admin/artists/'
    | '/_admin/history/'
    | '/_admin/subjects/'
    | '/_admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/rooms': {
      id: '/_admin/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/subjects/': {
      id: '/_admin/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AdminSubjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/history/': {
      id: '/_admin/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AdminHistoryIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/artists/': {
      id: '/_admin/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof AdminArtistsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/$userId': {
      id: '/_admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/subjects/$subjectId': {
      id: '/_admin/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof AdminSubjectsSubjectIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/history/$historyId': {
      id: '/_admin/history/$historyId'
      path: '/history/$historyId'
      fullPath: '/history/$historyId'
      preLoaderRoute: typeof AdminHistoryHistoryIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/artists/$artistId': {
      id: '/_admin/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof AdminArtistsArtistIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArtistsArtistIdRoute: typeof AdminArtistsArtistIdRoute
  AdminHistoryHistoryIdRoute: typeof AdminHistoryHistoryIdRoute
  AdminSubjectsSubjectIdRoute: typeof AdminSubjectsSubjectIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminArtistsIndexRoute: typeof AdminArtistsIndexRoute
  AdminHistoryIndexRoute: typeof AdminHistoryIndexRoute
  AdminSubjectsIndexRoute: typeof AdminSubjectsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRoomsRoute: AdminRoomsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArtistsArtistIdRoute: AdminArtistsArtistIdRoute,
  AdminHistoryHistoryIdRoute: AdminHistoryHistoryIdRoute,
  AdminSubjectsSubjectIdRoute: AdminSubjectsSubjectIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminArtistsIndexRoute: AdminArtistsIndexRoute,
  AdminHistoryIndexRoute: AdminHistoryIndexRoute,
  AdminSubjectsIndexRoute: AdminSubjectsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
