/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminSubjectsIndexRouteImport } from './routes/_admin.subjects.index'
import { Route as AdminArtistsIndexRouteImport } from './routes/_admin.artists.index'
import { Route as AdminSubjectsSubjectIdRouteImport } from './routes/_admin.subjects.$subjectId'
import { Route as AdminArtistsArtistIdRouteImport } from './routes/_admin.artists.$artistId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsIndexRoute = AdminSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistsIndexRoute = AdminArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsSubjectIdRoute = AdminSubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistsArtistIdRoute = AdminArtistsArtistIdRouteImport.update({
  id: '/artists/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/artists/$artistId': typeof AdminArtistsArtistIdRoute
  '/subjects/$subjectId': typeof AdminSubjectsSubjectIdRoute
  '/artists/': typeof AdminArtistsIndexRoute
  '/subjects/': typeof AdminSubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/': typeof AdminIndexRoute
  '/artists/$artistId': typeof AdminArtistsArtistIdRoute
  '/subjects/$subjectId': typeof AdminSubjectsSubjectIdRoute
  '/artists': typeof AdminArtistsIndexRoute
  '/subjects': typeof AdminSubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/artists/$artistId': typeof AdminArtistsArtistIdRoute
  '/_admin/subjects/$subjectId': typeof AdminSubjectsSubjectIdRoute
  '/_admin/artists/': typeof AdminArtistsIndexRoute
  '/_admin/subjects/': typeof AdminSubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/artists/$artistId'
    | '/subjects/$subjectId'
    | '/artists/'
    | '/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/'
    | '/artists/$artistId'
    | '/subjects/$subjectId'
    | '/artists'
    | '/subjects'
  id:
    | '__root__'
    | '/_admin'
    | '/forbidden'
    | '/login'
    | '/_admin/'
    | '/_admin/artists/$artistId'
    | '/_admin/subjects/$subjectId'
    | '/_admin/artists/'
    | '/_admin/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/subjects/': {
      id: '/_admin/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AdminSubjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/artists/': {
      id: '/_admin/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof AdminArtistsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/subjects/$subjectId': {
      id: '/_admin/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof AdminSubjectsSubjectIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/artists/$artistId': {
      id: '/_admin/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof AdminArtistsArtistIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArtistsArtistIdRoute: typeof AdminArtistsArtistIdRoute
  AdminSubjectsSubjectIdRoute: typeof AdminSubjectsSubjectIdRoute
  AdminArtistsIndexRoute: typeof AdminArtistsIndexRoute
  AdminSubjectsIndexRoute: typeof AdminSubjectsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminArtistsArtistIdRoute: AdminArtistsArtistIdRoute,
  AdminSubjectsSubjectIdRoute: AdminSubjectsSubjectIdRoute,
  AdminArtistsIndexRoute: AdminArtistsIndexRoute,
  AdminSubjectsIndexRoute: AdminSubjectsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
