/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AuthVerifyVerifyRouteImport } from './routes/auth.verify/verify'
import { Route as AppUUsernameRouteImport } from './routes/_app.u.$username'
import { Route as AppGamesGameTypeRouteImport } from './routes/_app.games.$gameType'
import { Route as AppGameCreateIndexRouteImport } from './routes/_app.game.create.index'
import { Route as AppGameCreateGameTypeRouteImport } from './routes/_app.game.create.$gameType'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyVerifyRoute = AuthVerifyVerifyRouteImport.update({
  id: '/auth/verify/verify',
  path: '/auth/verify/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUUsernameRoute = AppUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesGameTypeRoute = AppGamesGameTypeRouteImport.update({
  id: '/games/$gameType',
  path: '/games/$gameType',
  getParentRoute: () => AppRoute,
} as any)
const AppGameCreateIndexRoute = AppGameCreateIndexRouteImport.update({
  id: '/game/create/',
  path: '/game/create/',
  getParentRoute: () => AppRoute,
} as any)
const AppGameCreateGameTypeRoute = AppGameCreateGameTypeRouteImport.update({
  id: '/game/create/$gameType',
  path: '/game/create/$gameType',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/games/$gameType': typeof AppGamesGameTypeRoute
  '/u/$username': typeof AppUUsernameRoute
  '/auth/verify/verify': typeof AuthVerifyVerifyRoute
  '/game/create/$gameType': typeof AppGameCreateGameTypeRoute
  '/game/create/': typeof AppGameCreateIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/': typeof AppIndexRoute
  '/games/$gameType': typeof AppGamesGameTypeRoute
  '/u/$username': typeof AppUUsernameRoute
  '/auth/verify/verify': typeof AuthVerifyVerifyRoute
  '/game/create/$gameType': typeof AppGameCreateGameTypeRoute
  '/game/create': typeof AppGameCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/_app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/games/$gameType': typeof AppGamesGameTypeRoute
  '/_app/u/$username': typeof AppUUsernameRoute
  '/auth/verify/verify': typeof AuthVerifyVerifyRoute
  '/_app/game/create/$gameType': typeof AppGameCreateGameTypeRoute
  '/_app/game/create/': typeof AppGameCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/home'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/game/$gameId'
    | '/games/$gameType'
    | '/u/$username'
    | '/auth/verify/verify'
    | '/game/create/$gameType'
    | '/game/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/home'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/game/$gameId'
    | '/'
    | '/games/$gameType'
    | '/u/$username'
    | '/auth/verify/verify'
    | '/game/create/$gameType'
    | '/game/create'
  id:
    | '__root__'
    | '/_app'
    | '/dashboard'
    | '/home'
    | '/_app/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/game/$gameId'
    | '/_app/'
    | '/_app/games/$gameType'
    | '/_app/u/$username'
    | '/auth/verify/verify'
    | '/_app/game/create/$gameType'
    | '/_app/game/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  GameGameIdRoute: typeof GameGameIdRoute
  AuthVerifyVerifyRoute: typeof AuthVerifyVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/verify/verify': {
      id: '/auth/verify/verify'
      path: '/auth/verify/verify'
      fullPath: '/auth/verify/verify'
      preLoaderRoute: typeof AuthVerifyVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/u/$username': {
      id: '/_app/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AppUUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/$gameType': {
      id: '/_app/games/$gameType'
      path: '/games/$gameType'
      fullPath: '/games/$gameType'
      preLoaderRoute: typeof AppGamesGameTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/game/create/': {
      id: '/_app/game/create/'
      path: '/game/create'
      fullPath: '/game/create/'
      preLoaderRoute: typeof AppGameCreateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/game/create/$gameType': {
      id: '/_app/game/create/$gameType'
      path: '/game/create/$gameType'
      fullPath: '/game/create/$gameType'
      preLoaderRoute: typeof AppGameCreateGameTypeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGamesGameTypeRoute: typeof AppGamesGameTypeRoute
  AppUUsernameRoute: typeof AppUUsernameRoute
  AppGameCreateGameTypeRoute: typeof AppGameCreateGameTypeRoute
  AppGameCreateIndexRoute: typeof AppGameCreateIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppGamesGameTypeRoute: AppGamesGameTypeRoute,
  AppUUsernameRoute: AppUUsernameRoute,
  AppGameCreateGameTypeRoute: AppGameCreateGameTypeRoute,
  AppGameCreateIndexRoute: AppGameCreateIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  GameGameIdRoute: GameGameIdRoute,
  AuthVerifyVerifyRoute: AuthVerifyVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
