import dotenv from "dotenv";
import { defineConfig } from "drizzle-kit";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({
  path: "../../apps/server/.env",
});

// Find the local D1 database file generated by Alchemy/Wrangler
const getLocalD1Path = () => {
  const basePath = path.resolve(__dirname, "../../.alchemy/miniflare/v3/d1/miniflare-D1DatabaseObject");
  if (fs.existsSync(basePath)) {
    const files = fs.readdirSync(basePath).filter(f => f.endsWith(".sqlite"));
    const firstFile = files[0];
    if (firstFile) {
      return path.join(basePath, firstFile);
    }
  }
  return undefined;
};

const localDbPath = getLocalD1Path();

export default defineConfig({
  schema: "./src/schema",
  out: "./src/migrations",
  dialect: "sqlite",
  dbCredentials: {
    url: localDbPath ?? "local.sqlite",
  },
});
